import os
import re
import shutil
import tempfile

from pathlib import Path

from backend.app.core.paths import (
    PROJECT_ROOT,
)


# ==========================================================
# JOB SOURCE STORE
# PHASE 9.2
# ==========================================================
#
# Holds uploaded bytes between "the browser sent them" and "a
# worker processed them".
#
#
# WHY THIS CANNOT BE A TEMPORARY FILE
# ----------------------------------------------------------
#
# The synchronous endpoint used tempfile.NamedTemporaryFile
# and deleted it in a finally block, which was correct: the
# pipeline ran inside the request, so the file was needed for
# exactly the length of the request.
#
# Async breaks that. The request returns 202 immediately and a
# different process reads the file, possibly minutes later,
# possibly after an API restart. A temporary file cleaned up
# when the request ends would be gone before the worker
# opened it, and the failure mode would be a job that fails
# with SOURCE_MISSING under load and passes every test where
# the worker happens to be fast.
#
# So a pending upload is durable, deliberately, and is deleted
# by whoever finishes with it.
#
#
# WHY IT IS NOT UNDER THE MANAGED STORAGE ROOT
# ----------------------------------------------------------
#
# This is the important part, and it is a trap.
#
# StorageIntegrityService._scan_storage_root() iterates
# storage_root and classifies every entry it does not
# recognise. An entry whose name is not a document id in the
# database becomes ORPHAN_STORAGE -- and ORPHAN_STORAGE is the
# one classification StorageReconciliationService is allowed
# to delete automatically.
#
# A pending upload has no document row yet. That is the whole
# point of it. So putting pending uploads under the managed
# root would make every in-flight upload look exactly like an
# orphan, and reconciliation would delete documents while
# workers were still processing them -- correctly, according
# to its own rules, which is what makes it dangerous.
#
# Pending uploads therefore live in a sibling root:
#
#     storage/documents/    managed, reconciled, permanent
#     storage/pending/      in flight, never scanned
#
# Nothing in the integrity or reconciliation services is
# changed by this file. Their invariants were audited and
# should stay audited.
#
#
# WHAT IT KEEPS FROM THE MANAGED STORE
# ----------------------------------------------------------
#
# The same protections, because the input is just as
# untrusted: a strict name pattern, resolved-path containment
# so no name can escape the root, symlink rejection, and an
# atomic write via a temporary file in the same directory
# followed by os.replace.
# ==========================================================


class JobSourceSecurityError(
    RuntimeError
):
    """
    Raised when a source name or resolved path fails a safety
    check. Never carries the offending path, so it can be
    logged.
    """


DEFAULT_PENDING_ROOT = (
    PROJECT_ROOT
    / "storage"
    / "pending"
)


class JobSourceStore:

    # A pending name is generated by this class, never
    # supplied by a caller, so the pattern can be strict.
    # It is still enforced on the read path: a name arriving
    # from a database row is data, and data gets validated.
    SOURCE_NAME_PATTERN = (
        re.compile(
            r"^[A-Za-z0-9_-]{1,120}"
            r"(\.[A-Za-z0-9]{1,10})?$"
        )
    )

    def __init__(
        self,
        pending_root: str | Path | None = None,
    ) -> None:

        root = (
            Path(
                pending_root
            )
            if pending_root is not None
            else Path(
                os.getenv(
                    "DOCUMENT_PENDING_DIR",
                    "",
                )
                or DEFAULT_PENDING_ROOT
            )
        )

        self.pending_root = (
            root.resolve()
        )

        self.pending_root.mkdir(
            parents=True,
            exist_ok=True,
        )


        if not self.pending_root.is_dir():

            raise JobSourceSecurityError(
                "The pending upload root is not a "
                "directory."
            )


        # A symlinked root would mean every containment check
        # below compares against the wrong place.
        if self.pending_root.is_symlink():

            raise JobSourceSecurityError(
                "The pending upload root is a symbolic "
                "link."
            )


        self._assert_outside_managed_storage()


    def _assert_outside_managed_storage(
        self,
    ) -> None:

        """
        Refuse to start if pending uploads would sit inside
        the managed storage root.

        The defaults are siblings and are fine:

            storage/documents/   managed
            storage/pending/     in flight

        But both are configurable, and a deployment that set
        DOCUMENT_STORAGE_DIR to storage/ -- the parent -- would
        put every pending upload inside the reconciled tree.
        Reconciliation would then classify each one as
        ORPHAN_STORAGE, because a pending upload has no
        document row by definition, and delete it. Documents
        would vanish mid-processing, and reconciliation would
        be behaving exactly as specified while it happened.

        That is a data-loss configuration, so it is refused at
        construction rather than discovered in production.
        """

        from backend.app.services.document_storage_service import (
            DocumentStorageService,
        )

        try:
            managed_root = (
                DocumentStorageService()
                .storage_root
            )

        except Exception:      # noqa: BLE001
            # If the managed store cannot be constructed, that
            # is its own startup failure to report, not this
            # one. Nothing is silently skipped: the API's
            # readiness check owns that.
            return


        if self.pending_root == managed_root:

            raise JobSourceSecurityError(
                "The pending upload root and the managed "
                "storage root are the same directory. "
                "Pending uploads would be reconciled away "
                "as orphans while workers were still "
                "processing them."
            )


        if managed_root in self.pending_root.parents:

            raise JobSourceSecurityError(
                "The pending upload root is inside the "
                "managed storage root. Pending uploads "
                "would be reconciled away as orphans "
                "while workers were still processing "
                "them. Configure DOCUMENT_PENDING_DIR "
                "outside DOCUMENT_STORAGE_DIR."
            )


    # ======================================================
    # VALIDATION
    # ======================================================

    def validate_source_name(
        self,
        source_name: str,
    ) -> str:

        if not isinstance(
            source_name,
            str,
        ) or not source_name:

            raise JobSourceSecurityError(
                "A source name is required."
            )


        if source_name != source_name.strip():

            raise JobSourceSecurityError(
                "The source name has leading or "
                "trailing whitespace."
            )


        if not self.SOURCE_NAME_PATTERN.fullmatch(
            source_name
        ):

            raise JobSourceSecurityError(
                "Unsafe source name."
            )


        return source_name


    def _resolve_safe_path(
        self,
        source_name: str,
    ) -> Path:

        validated = (
            self.validate_source_name(
                source_name
            )
        )

        candidate = (
            self.pending_root
            / validated
        )

        # Resolve before comparing. A name that survived the
        # pattern check still has to land inside the root once
        # the filesystem has had its say -- on a case-
        # insensitive filesystem, or through a symlinked
        # component, those are different questions.
        resolved = (
            candidate.resolve()
        )


        if resolved.parent != self.pending_root:

            raise JobSourceSecurityError(
                "The resolved pending path escapes the "
                "pending root."
            )


        if resolved == self.pending_root:

            raise JobSourceSecurityError(
                "The resolved pending path is the root "
                "itself."
            )


        return resolved


    # ======================================================
    # WRITE
    # ======================================================

    def save_pending(
        self,
        *,
        source_name: str,
        source_path: str | Path,
    ) -> Path:

        """
        Move an already-written upload into the pending store
        atomically.

        source_path is the bounded temporary file the request
        handler streamed the upload into. It is consumed:
        after this returns, the bytes live under the pending
        root and the temporary file is gone.
        """

        destination = (
            self._resolve_safe_path(
                source_name
            )
        )

        origin = (
            Path(
                source_path
            )
        )


        if not origin.is_file():

            raise JobSourceSecurityError(
                "The upload to store does not exist."
            )


        if origin.is_symlink():

            raise JobSourceSecurityError(
                "The upload to store is a symbolic "
                "link."
            )


        # Written into the destination directory first so that
        # os.replace stays on one filesystem and therefore
        # stays atomic. A partially written pending file must
        # never be visible under its real name, because a
        # worker could claim the job and read it mid-write.
        temp_path: Path | None = None


        try:

            with tempfile.NamedTemporaryFile(
                mode="wb",
                delete=False,
                dir=self.pending_root,
                prefix=".pending_",
                suffix=".tmp",
            ) as temp_file:

                temp_path = (
                    Path(
                        temp_file.name
                    )
                )

                with origin.open(
                    "rb"
                ) as source_file:

                    shutil.copyfileobj(
                        source_file,
                        temp_file,
                    )


                temp_file.flush()

                os.fsync(
                    temp_file.fileno()
                )


            os.replace(
                temp_path,
                destination,
            )

            temp_path = None


        finally:

            # A failed write must not leave a .pending_*.tmp
            # behind. Nothing else cleans this directory, and
            # an accumulating temp file is a disk-full
            # incident with a slow fuse.
            if (
                temp_path is not None
                and temp_path.exists()
            ):
                temp_path.unlink(
                    missing_ok=True,
                )


        # The origin was a bounded temporary file owned by the
        # request. Its bytes are safely stored now.
        origin.unlink(
            missing_ok=True,
        )

        return destination


    # ======================================================
    # READ
    # ======================================================

    def pending_path(
        self,
        source_name: str,
    ) -> Path:

        return (
            self._resolve_safe_path(
                source_name
            )
        )


    def exists(
        self,
        source_name: str,
    ) -> bool:

        try:
            path = (
                self._resolve_safe_path(
                    source_name
                )
            )

        except JobSourceSecurityError:
            return False


        return (
            path.is_file()
            and not path.is_symlink()
        )


    # ======================================================
    # DELETE
    # ======================================================

    def delete_pending(
        self,
        source_name: str,
    ) -> bool:

        """
        Remove a pending upload.

        Called when a job reaches a terminal state, whether it
        succeeded or failed. A failed job that keeps its
        upload forever is a privacy problem as much as a disk
        one: these are identity documents.
        """

        try:
            path = (
                self._resolve_safe_path(
                    source_name
                )
            )

        except JobSourceSecurityError:
            # An unsafe name cannot name a file this store
            # wrote, so there is nothing of ours to delete.
            return False


        if path.is_symlink():

            raise JobSourceSecurityError(
                "Refusing to delete through a symbolic "
                "link."
            )


        if not path.is_file():
            return False


        path.unlink()

        return True


    # ======================================================
    # MAINTENANCE
    # ======================================================

    def orphaned_names(
        self,
        known_names: set[str],
    ) -> list[str]:

        """
        Pending files that no job row refers to any more.

        Reported, never deleted here. Deletion is an explicit
        operational action in
        scripts/maintenance/, deliberately mirroring the
        managed store's rule that reconciliation only ever
        removes what it can prove is unreferenced -- and
        deliberately not repeating the mistake this class
        exists to avoid.
        """

        found: list[str] = []


        for entry in self.pending_root.iterdir():

            if not entry.is_file():
                continue

            # Temporary files belong to an in-flight write.
            if entry.name.startswith(
                ".pending_"
            ):
                continue

            if entry.name in known_names:
                continue


            found.append(
                entry.name
            )


        return sorted(
            found
        )
